// Full Nationality Options
export const countryOptions  = [
  { value: "", label: "Select Nationality" },
  { value: "Any Arabic National", label: "Any Arabic National" },
  { value: "Any GCC National", label: "Any GCC National" },
  { value: "Any European National", label: "Any European National" },
  { value: "Bahraini", label: "Bahraini" },
  { value: "Egyptian", label: "Egyptian" },
  { value: "Indian", label: "Indian" },
  { value: "Jordanian", label: "Jordanian" },
  { value: "Kuwaiti", label: "Kuwaiti" },
  { value: "Lebanese", label: "Lebanese" },
  { value: "Omani", label: "Omani" },
  { value: "Palestinian", label: "Palestinian" },
  { value: "Qatari", label: "Qatari" },
  { value: "Saudi Arabian", label: "Saudi Arabian" },
  { value: "Tunisian", label: "Tunisian" },
  { value: "Emirati (UAE)", label: "Emirati (UAE)" },
  { value: "Afghan", label: "Afghan" },
  { value: "Albanian", label: "Albanian" },
  { value: "Algerian", label: "Algerian" },
  { value: "American (US)", label: "American (US)" },
  { value: "Angolan", label: "Angolan" },
  { value: "Argentine", label: "Argentine" },
  { value: "Armenian", label: "Armenian" },
  { value: "Australian", label: "Australian" },
  { value: "Austrian", label: "Austrian" },
  { value: "Azerbaijani", label: "Azerbaijani" },
  { value: "Bangladeshi", label: "Bangladeshi" },
  { value: "Barbadian", label: "Barbadian" },
  { value: "Belarusian", label: "Belarusian" },
  { value: "Belgian", label: "Belgian" },
  { value: "Belizean", label: "Belizean" },
  { value: "Beninese", label: "Beninese" },
  { value: "Bosnian", label: "Bosnian" },
  { value: "Brazilian", label: "Brazilian" },
  { value: "British (UK)", label: "British (UK)" },
  { value: "Bruneian", label: "Bruneian" },
  { value: "Bulgarian", label: "Bulgarian" },
  { value: "Burkinabe", label: "Burkinabe" },
  { value: "Burmese", label: "Burmese" },
  { value: "Burundian", label: "Burundian" },
  { value: "Cameroonian", label: "Cameroonian" },
  { value: "Canadian", label: "Canadian" },
  { value: "Cayman", label: "Cayman" },
  { value: "Central African National", label: "Central African National" },
  { value: "Chadian", label: "Chadian" },
  { value: "Chilean", label: "Chilean" },
  { value: "Chinese", label: "Chinese" },
  { value: "Colombian", label: "Colombian" },
  { value: "Comorian", label: "Comorian" },
  { value: "Congolese", label: "Congolese" },
  { value: "Costa Rican", label: "Costa Rican" },
  { value: "Croat", label: "Croat" },
  { value: "Cuban", label: "Cuban" },
  { value: "Cypriot", label: "Cypriot" },
  { value: "Czech", label: "Czech" },
  { value: "Danish", label: "Danish" },
  { value: "Djiboutian", label: "Djiboutian" },
  { value: "Dominican", label: "Dominican" },
  { value: "Dutch (Netherlands Antilles)", label: "Dutch (Netherlands Antilles)" },
  { value: "Ecuadorian", label: "Ecuadorian" },
  { value: "Eritrean", label: "Eritrean" },
  { value: "Estonian", label: "Estonian" },
  { value: "Ethiopian", label: "Ethiopian" },
  { value: "Fijian", label: "Fijian" },
  { value: "Filipino", label: "Filipino" },
  { value: "Finnish", label: "Finnish" },
  { value: "French", label: "French" },
  { value: "Gabonese", label: "Gabonese" },
  { value: "Gambian", label: "Gambian" },
  { value: "Georgian", label: "Georgian" },
  { value: "German", label: "German" },
  { value: "Ghanaian", label: "Ghanaian" },
  { value: "Greek", label: "Greek" },
  { value: "Guatemalan", label: "Guatemalan" },
  { value: "Guyanese", label: "Guyanese" },
  { value: "Haitian", label: "Haitian" },
  { value: "Honduran", label: "Honduran" },
  { value: "Hungarian", label: "Hungarian" },
  { value: "Icelandic", label: "Icelandic" },
  { value: "Indonesian", label: "Indonesian" },
  { value: "Iranian", label: "Iranian" },
  { value: "Iraqi", label: "Iraqi" },
  { value: "Irish", label: "Irish" },
  { value: "Italian", label: "Italian" },
  { value: "Ivorian", label: "Ivorian" },
  { value: "Jamaican", label: "Jamaican" },
  { value: "Japanese", label: "Japanese" },
  { value: "Kazakh", label: "Kazakh" },
  { value: "Kenyan", label: "Kenyan" },
  { value: "Korean (North)", label: "Korean (North)" },
  { value: "Korean (South)", label: "Korean (South)" },
  { value: "Kyrgyz", label: "Kyrgyz" },
  { value: "Laotian", label: "Laotian" },
  { value: "Latvian", label: "Latvian" },
  { value: "Liberian", label: "Liberian" },
  { value: "Libyan", label: "Libyan" },
  { value: "Lithuanian", label: "Lithuanian" },
  { value: "Luxembourger", label: "Luxembourger" },
  { value: "Macedonian", label: "Macedonian" },
  { value: "Malagasy", label: "Malagasy" },
  { value: "Malawian", label: "Malawian" },
  { value: "Malaysian", label: "Malaysian" },
  { value: "Maldivian", label: "Maldivian" },
  { value: "Malian", label: "Malian" },
  { value: "Maltese", label: "Maltese" },
  { value: "Mauritanian", label: "Mauritanian" },
  { value: "Mauritian", label: "Mauritian" },
  { value: "Mexican", label: "Mexican" },
  { value: "Moldovan", label: "Moldovan" },
  { value: "Monegasque", label: "Monegasque" },
  { value: "Mongolian", label: "Mongolian" },
  { value: "Montenegrin", label: "Montenegrin" },
  { value: "Moroccan", label: "Moroccan" },
  { value: "Motswana", label: "Motswana" },
  { value: "Mozambican", label: "Mozambican" },
  { value: "Namibian", label: "Namibian" },
  { value: "Nepali", label: "Nepali" },
  { value: "New Zealander", label: "New Zealander" },
  { value: "Nicaraguan", label: "Nicaraguan" },
  { value: "Nigerian (Nigeria)", label: "Nigerian (Nigeria)" },
  { value: "Nigerien (Niger)", label: "Nigerien (Niger)" },
  { value: "Norwegian", label: "Norwegian" },
  { value: "Pakistani", label: "Pakistani" },
  { value: "Panamanian", label: "Panamanian" },
  { value: "Paraguayan", label: "Paraguayan" },
  { value: "Peruvian", label: "Peruvian" },
  { value: "Polish", label: "Polish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "Puerto Rican", label: "Puerto Rican" },
  { value: "Romanian", label: "Romanian" },
  { value: "Russian", label: "Russian" },
  { value: "Rwandan", label: "Rwandan" },
  { value: "Sahrawi", label: "Sahrawi" },
  { value: "Salvadoran", label: "Salvadoran" },
  { value: "Sammarinese", label: "Sammarinese" },
  { value: "Samoan", label: "Samoan" },
  { value: "Senegalese", label: "Senegalese" },
  { value: "Serbian", label: "Serbian" },
  { value: "Seychellois", label: "Seychellois" },
  { value: "Sierra Leonean", label: "Sierra Leonean" },
  { value: "Singaporean", label: "Singaporean" },
  { value: "Slovak", label: "Slovak" },
  { value: "Slovenes", label: "Slovenes" },
  { value: "Somali", label: "Somali" },
  { value: "South African", label: "South African" },
  { value: "Spanish", label: "Spanish" },
  { value: "Sri Lankan", label: "Sri Lankan" },
  { value: "Sudanese", label: "Sudanese" },
  { value: "Swazi", label: "Swazi" },
  { value: "Swedish", label: "Swedish" },
  { value: "Swiss", label: "Swiss" },
  { value: "Syrian", label: "Syrian" },
  { value: "Taiwanese", label: "Taiwanese" },
  { value: "Tajiki", label: "Tajiki" },
  { value: "Tanzanian", label: "Tanzanian" },
  { value: "Thai", label: "Thai" },
  { value: "Timorese", label: "Timorese" },
  { value: "Tongan", label: "Tongan" },
  { value: "Trini", label: "Trini" },
  { value: "Turkish", label: "Turkish" },
  { value: "Turkmen", label: "Turkmen" },
  { value: "Ugandan", label: "Ugandan" },
  { value: "Ukrainian", label: "Ukrainian" },
  { value: "Uruguayan", label: "Uruguayan" },
  { value: "Uzbek", label: "Uzbek" },
  { value: "Vatican Citizen", label: "Vatican Citizen" },
  { value: "Venezuelan", label: "Venezuelan" },
  { value: "Vietnamese", label: "Vietnamese" },
  { value: "Yemeni", label: "Yemeni" },
  { value: "Zambian", label: "Zambian" },
  { value: "Zimbabwean", label: "Zimbabwean" },
];

// Industry Options
export const industryOptions = [
  { value: "Academic Institutions", label: "Academic Institutions" },
  { value: "Accounting & Tax", label: "Accounting & Tax" },
  { value: "Advertising & Publishing Relation", label: "Advertising & Publishing Relation" },
  { value: "Air Freight And Logistics", label: "Air Freight And Logistics" },
  { value: "Airlines", label: "Airlines" },
  { value: "Airports", label: "Airports" },
  { value: "Ambulance & Medical Transportation", label: "Ambulance & Medical Transportation" },
  { value: "Animal Production", label: "Animal Production" },
  { value: "Architectural & Engineering Services", label: "Architectural & Engineering Services" },
  { value: "Architecture", label: "Architecture" },
  { value: "Art Performing", label: "Art Performing" },
  { value: "Arts & Culture", label: "Arts & Culture" },
  { value: "Athleisure", label: "Athleisure" },
  { value: "Automotive", label: "Automotive" },
  { value: "Audience & Fan Attention", label: "Audience & Fan Attention" },
  { value: "Banking & Lending", label: "Banking & Lending" },
  { value: "Bars & Night Clubs", label: "Bars & Night Clubs" },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Books", label: "Books" },
  { value: "Broadcast Media", label: "Broadcast Media" },
  { value: "Building & Construction", label: "Building & Construction" },
  { value: "Building Material", label: "Building Material" },
  { value: "Building Services", label: "Building Services" },
  { value: "Catering & Food Services Contractor", label: "Catering & Food Services Contractor" },
  { value: "Chemical", label: "Chemical" },
  { value: "Chemical Manufacturing", label: "Chemical Manufacturing" },
  { value: "Chemicals", label: "Chemicals" },
  { value: "Civil & Social Services", label: "Civil & Social Services" },
  { value: "Clean Beauty", label: "Clean Beauty" },
  { value: "Clothing And Accessories", label: "Clothing And Accessories" },
  { value: "Coal", label: "Coal" },
  { value: "Colleges & Universities", label: "Colleges & Universities" },
  { value: "Commercial", label: "Commercial" },
  { value: "Commercial Art", label: "Commercial Art" },
  { value: "Commercial Equipment Services", label: "Commercial Equipment Services" },
  { value: "Commercial Real Estate", label: "Commercial Real Estate" },
  { value: "Communication And Broadcasting Equipment", label: "Communication And Broadcasting Equipment" },
  { value: "Communications Equipment", label: "Communications Equipment" },
  { value: "Computers", label: "Computers" },
  { value: "Construction & Repair Services", label: "Construction & Repair Services" },
  { value: "Consulting & Professional Services", label: "Consulting & Professional Services" },
  { value: "Consumer Electronics", label: "Consumer Electronics" },
  { value: "Consumer Products", label: "Consumer Products" },
  { value: "Contracting", label: "Contracting" },
  { value: "Corp Production", label: "Corp Production" },
  { value: "Corporation Services", label: "Corporation Services" },
  { value: "Crushed Stone", label: "Crushed Stone" },
  { value: "Culture & Entertainment", label: "Culture & Entertainment" },
  { value: "Cultural And Recreation", label: "Cultural And Recreation" },
  { value: "Dance", label: "Dance" },
  { value: "Dental Clinic", label: "Dental Clinic" },
  { value: "Dermatologist & Cosmetologist", label: "Dermatologist & Cosmetologist" },
  { value: "Design", label: "Design" },
  { value: "Digital", label: "Digital" },
  { value: "Digital Fitness", label: "Digital Fitness" },
  { value: "Digital Media", label: "Digital Media" },
  { value: "Digital Music Distribution", label: "Digital Music Distribution" },
  { value: "Drilling", label: "Drilling" },
  { value: "Drug Manufacturers", label: "Drug Manufacturers" },
  { value: "Drug Marketers", label: "Drug Marketers" },
  { value: "Education", label: "Education" },
  { value: "Education & Training", label: "Education & Training" },
  { value: "Education & Training Services", label: "Education & Training Services" },
  { value: "Education Consultants", label: "Education Consultants" },
  { value: "Education Information And Research", label: "Education Information And Research" },
  { value: "Education Investment Services", label: "Education Investment Services" },
  { value: "Education Support Services", label: "Education Support Services" },
  { value: "Educational Products & Publishing", label: "Educational Products & Publishing" },
  { value: "Electronic Components", label: "Electronic Components" },
  { value: "Electronics", label: "Electronics" },
  { value: "Electronics And Appliance S", label: "Electronics And Appliance S" },
  { value: "Energy", label: "Energy" },
  { value: "Energy Utilities", label: "Energy Utilities" },
  { value: "Engineering & Construction", label: "Engineering & Construction" },
  { value: "Engineering Firms", label: "Engineering Firms" },
  { value: "Environment And Animals", label: "Environment And Animals" },
  { value: "Environmental", label: "Environmental" },
  { value: "Equipment & Services", label: "Equipment & Services" },
  { value: "Event", label: "Event" },
  { value: "Exploring & Production", label: "Exploring & Production" },
  { value: "Facility Management", label: "Facility Management" },
  { value: "Farm Support", label: "Farm Support" },
  { value: "Fashion", label: "Fashion" },
  { value: "Films", label: "Films" },
  { value: "Film Production", label: "Film Production" },
  { value: "Financial", label: "Financial" },
  { value: "Financial Transaction Process", label: "Financial Transaction Process" },
  { value: "Fine Art & Crafts", label: "Fine Art & Crafts" },
  { value: "Fishery", label: "Fishery" },
  { value: "Floral Nursery", label: "Floral Nursery" },
  { value: "Food & Beverage", label: "Food & Beverage" },
  { value: "Food & Beverages", label: "Food & Beverages" },
  { value: "Forestry", label: "Forestry" },
  { value: "Foreign Telecom Services", label: "Foreign Telecom Services" },
  { value: "Furniture And Home Furnishings", label: "Furniture And Home Furnishings" },
  { value: "Game Development", label: "Game Development" },
  { value: "Geotechnical", label: "Geotechnical" },
  { value: "Government", label: "Government" },
  { value: "Government Organizations", label: "Government Organizations" },
  { value: "Government Services", label: "Government Services" },
  { value: "Grantmaking & Charitable Foundation", label: "Grantmaking & Charitable Foundation" },
  { value: "Health And Personal Care", label: "Health And Personal Care" },
  { value: "Health Care", label: "Health Care" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Healthcare Practices", label: "Healthcare Practices" },
  { value: "Health Insurance Carriers", label: "Health Insurance Carriers" },
  { value: "Health & Safety", label: "Health & Safety" },
  { value: "Highways", label: "Highways" },
  { value: "Home & Outdoor Sport", label: "Home & Outdoor Sport" },
  { value: "Hospital", label: "Hospital" },
  { value: "Hospitality & Tourism", label: "Hospitality & Tourism" },
  { value: "Hotels", label: "Hotels" },
  { value: "Household & Equipment", label: "Household & Equipment" },
  { value: "Human Resources", label: "Human Resources" },
  { value: "Human Services", label: "Human Services" },
  { value: "Humanities", label: "Humanities" },
  { value: "Industrial Electronics", label: "Industrial Electronics" },
  { value: "Industrial Minerals", label: "Industrial Minerals" },
  { value: "Industrial Real Estate", label: "Industrial Real Estate" },
  { value: "Information And Communications", label: "Information And Communications" },
  { value: "Information Technology", label: "Information Technology" },
  { value: "Information Technology Support Services", label: "Information Technology Support Services" },
  { value: "Insurance", label: "Insurance" },
  { value: "Insurance Agencies & Brokerage", label: "Insurance Agencies & Brokerage" },
  { value: "Insurance Carriers", label: "Insurance Carriers" },
  { value: "Internet & Webpage", label: "Internet & Webpage" },
  { value: "Investment & Asset Management", label: "Investment & Asset Management" },
  { value: "Irrigation & Greenhouses", label: "Irrigation & Greenhouses" },
  { value: "Law Firms", label: "Law Firms" },
  { value: "Legal Services", label: "Legal Services" },
  { value: "Licensing And Sync", label: "Licensing And Sync" },
  { value: "Live And Touring", label: "Live And Touring" },
  { value: "Luxury Services", label: "Luxury Services" },
  { value: "Machinery", label: "Machinery" },
  { value: "Management & Operations", label: "Management & Operations" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Mass Sport", label: "Mass Sport" },
  { value: "Medical & Testing Clinical Laboratories", label: "Medical & Testing Clinical Laboratories" },
  { value: "Medical Devices Services", label: "Medical Devices Services" },
  { value: "Metal", label: "Metal" },
  { value: "Metal & Iron", label: "Metal & Iron" },
  { value: "Mining", label: "Mining" },
  { value: "Mining & Resources", label: "Mining & Resources" },
  { value: "Motor Vehicle And Parts", label: "Motor Vehicle And Parts" },
  { value: "Movies", label: "Movies" },
  { value: "Music", label: "Music" },
  { value: "Music Companies", label: "Music Companies" },
  { value: "Music Conferences", label: "Music Conferences" },
  { value: "Nursing Care", label: "Nursing Care" },
  { value: "Native Sport", label: "Native Sport" },
  { value: "News", label: "News" },
  { value: "Newspapers & Magazines", label: "Newspapers & Magazines" },
  { value: "Occuptional Therapist", label: "Occuptional Therapist" },
  { value: "Oil & Gas", label: "Oil & Gas" },
  { value: "Paper Manufacturing", label: "Paper Manufacturing" },
  { value: "Personal Care", label: "Personal Care" },
  { value: "Pharmaceutical", label: "Pharmaceutical" },
  { value: "Photography", label: "Photography" },
  { value: "Physicians", label: "Physicians" },
  { value: "Physiotherapists", label: "Physiotherapists" },
  { value: "Pipeline And Refining", label: "Pipeline And Refining" },
  { value: "Plant-Based", label: "Plant-Based" },
  { value: "Pre Schools & Child Care Services", label: "Pre Schools & Child Care Services" },
  { value: "Primary & Secondary School", label: "Primary & Secondary School" },
  { value: "Project Management", label: "Project Management" },
  { value: "Property Management", label: "Property Management" },
  { value: "Quality", label: "Quality" },
  { value: "Radio", label: "Radio" },
  { value: "Radio Shows", label: "Radio Shows" },
  { value: "Rail Tracks", label: "Rail Tracks" },
  { value: "Railroads", label: "Railroads" },
  { value: "Real Estate Agencies", label: "Real Estate Agencies" },
  { value: "Recording", label: "Recording" },
  { value: "Registered Nurses", label: "Registered Nurses" },
  { value: "Religious Institutions", label: "Religious Institutions" },
  { value: "Residential Real Estate", label: "Residential Real Estate" },
  { value: "Restaurant & Cafes", label: "Restaurant & Cafes" },
  { value: "Roads & Bridge", label: "Roads & Bridge" },
  { value: "Sand And Gravel", label: "Sand And Gravel" },
  { value: "Sketch And Drawing", label: "Sketch And Drawing" },
  { value: "Software & Hardware Development", label: "Software & Hardware Development" },
  { value: "Sporting Goods", label: "Sporting Goods" },
  { value: "Staffing & Recruiting", label: "Staffing & Recruiting" },
  { value: "Stock Exchange", label: "Stock Exchange" },
  { value: "Strategy", label: "Strategy" },
  { value: "Streaming", label: "Streaming" },
  { value: "Team & Group Sport", label: "Team & Group Sport" },
  { value: "Technical & Corporate", label: "Technical & Corporate" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Textiles", label: "Textiles" },
  { value: "Theaters & Stages", label: "Theaters & Stages" },
  { value: "Ticket Sales", label: "Ticket Sales" },
  { value: "Toys & Games", label: "Toys & Games" },
  { value: "Tourism Sport", label: "Tourism Sport" },
  { value: "Translation", label: "Translation" },
  { value: "Travel And Tourism", label: "Travel And Tourism" },
  { value: "Trucking", label: "Trucking" },
  { value: "TV Shows", label: "TV Shows" },
  { value: "UPVC & Aluminum Manufacturing", label: "UPVC & Aluminum Manufacturing" },
  { value: "Vehicle Manufacturing", label: "Vehicle Manufacturing" },
  { value: "Vehicles Dealers", label: "Vehicles Dealers" },
  { value: "Vehicles Repair & Maintenance", label: "Vehicles Repair & Maintenance" },
  { value: "Video Game", label: "Video Game" },
  { value: "Wireless Communications", label: "Wireless Communications" },
  { value: "Wood", label: "Wood" },
  { value: "Written And Published Works", label: "Written And Published Works" },
  { value: "Other", label: "Other" },
];

export const currentPositionOptions = [
  { value: "", label: "Select Current Position" },
  { value: "Physician Assistant", label: "Physician Assistant" },
  { value: "Software Developer", label: "Software Developer" },
  { value: "Nurse Practitioner", label: "Nurse Practitioner" },
  { value: "Medical and Health Services Manager", label: "Medical and Health Services Manager" },
  { value: "Physician", label: "Physician" },
  { value: "Statistician", label: "Statistician" },
  { value: "Pathologist", label: "Pathologist" },
  { value: "Data entry", label: "Data entry" },
  { value: "Dentist", label: "Dentist" },
  { value: "Veterinarian", label: "Veterinarian" },
  { value: "Orthodontist", label: "Orthodontist" },
  { value: "IT Manager", label: "IT Manager" },
  { value: "Physical Therapist Assistant", label: "Physical Therapist Assistant" },
  { value: "Anaesthesiologist", label: "Anaesthesiologist" },
  { value: "Information Security Analyst", label: "Information Security Analyst" },
  { value: "Financial Manager", label: "Financial Manager" },
  { value: "Sales", label: "Sales" },
  { value: "Teacher", label: "Teacher" },
  { value: "Accountant", label: "Accountant" },
  { value: "Secretary", label: "Secretary" },
  { value: "Mechanical Engineer", label: "Mechanical Engineer" },
  { value: "Electrical Engineer", label: "Electrical Engineer" },
  { value: "Civil Engineer", label: "Civil Engineer" },
  { value: "Mining Engineer", label: "Mining Engineer" },
  { value: "Mechatronics Engineer", label: "Mechatronics Engineer" },
  { value: "Aerospace Engineer", label: "Aerospace Engineer" },
  { value: "Architect Engineer", label: "Architect Engineer" },
  { value: "Admin Manager", label: "Admin Manager" },
  { value: "Receptionist", label: "Receptionist" },
  { value: "Designer", label: "Designer" },
  { value: "Other", label: "Other" },
];

export const newCountryOptions = [
  { value: "", label: "Select Country" },
  { value: "Algeria", label: "Algeria" },
  { value: "Angola", label: "Angola" },
  { value: "Benin", label: "Benin" },
  { value: "Botswana", label: "Botswana" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cabo Verde", label: "Cabo Verde" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Central African Republic", label: "Central African Republic" },
  { value: "Chad", label: "Chad" },
  { value: "Comoros", label: "Comoros" },
  { value: "Congo (Republic of the)", label: "Congo (Republic of the)" },
  { value: "Congo (Democratic Republic of the)", label: "Congo (Democratic Republic of the)" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Egypt", label: "Egypt" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Eswatini", label: "Eswatini" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Gabon", label: "Gabon" },
  { value: "Gambia", label: "Gambia" },
  { value: "Ghana", label: "Ghana" },
  { value: "Guinea", label: "Guinea" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Ivory Coast (Côte d’Ivoire)", label: "Ivory Coast (Côte d’Ivoire)" },
  { value: "Kenya", label: "Kenya" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberia", label: "Liberia" },
  { value: "Libya", label: "Libya" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Malawi", label: "Malawi" },
  { value: "Mali", label: "Mali" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Morocco", label: "Morocco" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Namibia", label: "Namibia" },
  { value: "Niger", label: "Niger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "São Tomé and Príncipe", label: "São Tomé and Príncipe" },
  { value: "Senegal", label: "Senegal" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "Somalia", label: "Somalia" },
  { value: "South Africa", label: "South Africa" },
  { value: "South Sudan", label: "South Sudan" },
  { value: "Sudan", label: "Sudan" },
  { value: "Tanzania", label: "Tanzania" },
  { value: "Togo", label: "Togo" },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Uganda", label: "Uganda" },
  { value: "Zambia", label: "Zambia" },
  { value: "Zimbabwe", label: "Zimbabwe" },
  { value: "Afghanistan", label: "Afghanistan" },
  { value: "Armenia", label: "Armenia" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Brunei", label: "Brunei" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "China", label: "China" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Georgia", label: "Georgia" },
  { value: "India", label: "India" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Iran", label: "Iran" },
  { value: "Iraq", label: "Iraq" },
  { value: "Israel", label: "Israel" },
  { value: "Japan", label: "Japan" },
  { value: "Jordan", label: "Jordan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Laos", label: "Laos" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Maldives", label: "Maldives" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Myanmar (Burma)", label: "Myanmar (Burma)" },
  { value: "Nepal", label: "Nepal" },
  { value: "North Korea", label: "North Korea" },
  { value: "Oman", label: "Oman" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Palestine", label: "Palestine" },
  { value: "Philippines", label: "Philippines" },
  { value: "Qatar", label: "Qatar" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Singapore", label: "Singapore" },
  { value: "South Korea", label: "South Korea" },
  { value: "Sri Lanka", label: "Sri Lanka" },
  { value: "Syria", label: "Syria" },
  { value: "Taiwan", label: "Taiwan" },
  { value: "Tajikistan", label: "Tajikistan" },
  { value: "Thailand", label: "Thailand" },
  { value: "Timor-Leste (East Timor)", label: "Timor-Leste (East Timor)" },
  { value: "Turkey", label: "Turkey" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "Uzbekistan", label: "Uzbekistan" },
  { value: "Vietnam", label: "Vietnam" },
  { value: "Yemen", label: "Yemen" },
  { value: "Albania", label: "Albania" },
  { value: "Andorra", label: "Andorra" },
  { value: "Austria", label: "Austria" },
  { value: "Belarus", label: "Belarus" },
  { value: "Belgium", label: "Belgium" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Croatia", label: "Croatia" },
  { value: "Czech Republic (Czechia)", label: "Czech Republic (Czechia)" },
  { value: "Denmark", label: "Denmark" },
  { value: "Estonia", label: "Estonia" },
  { value: "Finland", label: "Finland" },
  { value: "France", label: "France" },
  { value: "Germany", label: "Germany" },
  { value: "Greece", label: "Greece" },
  { value: "Hungary", label: "Hungary" },
  { value: "Iceland", label: "Iceland" },
  { value: "Ireland", label: "Ireland" },
  { value: "Italy", label: "Italy" },
  { value: "Kosovo", label: "Kosovo" },
  { value: "Latvia", label: "Latvia" },
  { value: "Liechtenstein", label: "Liechtenstein" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Malta", label: "Malta" },
  { value: "Moldova", label: "Moldova" },
  { value: "Monaco", label: "Monaco" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "North Macedonia", label: "North Macedonia" },
  { value: "Norway", label: "Norway" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "Romania", label: "Romania" },
  { value: "Russia", label: "Russia" },
  { value: "San Marino", label: "San Marino" },
  { value: "Serbia", label: "Serbia" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Spain", label: "Spain" },
  { value: "Sweden", label: "Sweden" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belize", label: "Belize" },
  { value: "Canada", label: "Canada" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Dominica", label: "Dominica" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Grenada", label: "Grenada" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Haiti", label: "Haiti" },
  { value: "Honduras", label: "Honduras" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Mexico", label: "Mexico" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Panama", label: "Panama" },
  { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { value: "Saint Lucia", label: "Saint Lucia" },
  { value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
  { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { value: "United States", label: "United States" },
  { value: "Argentina", label: "Argentina" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Brazil", label: "Brazil" },
  { value: "Chile", label: "Chile" },
  { value: "Colombia", label: "Colombia" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Guyana", label: "Guyana" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Peru", label: "Peru" },
  { value: "Suriname", label: "Suriname" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Australia", label: "Australia" },
  { value: "Fiji", label: "Fiji" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Marshall Islands", label: "Marshall Islands" },
  { value: "Micronesia (Federated States of)", label: "Micronesia (Federated States of)" },
  { value: "Nauru", label: "Nauru" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Palau", label: "Palau" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Samoa", label: "Samoa" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "Tonga", label: "Tonga" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Vanuatu", label: "Vanuatu" }
];